region              = "us-east-1"
environment         = "dev"
vpc_cidr            = "10.0.0.0/16"
public_subnet_cidr  = "10.0.1.0/24"
private_subnet_cidr = "10.0.2.0/24"
availability_zone   = "us-east-1a"
instance_type       = "t2.micro"
ssh_public_key_path = "~/.ssh/id_rsa.pub"